export const ADD_DESK = 'ADD_DESK';
export const DELETE_DESK = 'DELETE_DESK';
export const ADD_PRAYER = 'ADD_PRAYER';
export const DELETE_PRAYER = 'DELETE_PRAYER';
export const MAKE_PRAYER_ANSWER = 'MAKE_PRAYER_ANSWER';
export const FLAG_ANSWERED_PRAYERS = 'FLAG_ANSWERED_PRAYERS';
export const MAKE_SUB_PRAYER_ANSWER = 'MAKE_SUB_PRAYER_ANSWER';
export const ADD_COMMENT = 'ADD_COMMENT';